x-veld:
  executable:
    about:
      description: "dummy veld for testing and showcasing"
    input/output:
      type: "BaseX http endpoint"
      url_path: "/rest"
      port: 8984
    storage:
      path: /veld/storage
      type: "BaseX Storage"
    docker_context:
      type: "docker network"
      optional: true

services:
  veld:
    build: .
    ports:
      - 8984:8984
    healthcheck:
      test: curl -f admin:admin@localhost:8984/rest
      interval: 5s
      timeout: 5s
      retries: 1
      start_period: 5s
    command: basexhttp
