x-veld:
  executable:
    about:
      description: "example veld for testing and showcasing"
    topics: "data persistence"
    input/output:
      a:
        type: "files"
        format: "BaseX Storage"
        path: /veld/storage/
      b:
        type: 
          - "BaseX HTTP endpoint"
          - "REST API"
        format: "xml"
        url_path: "/rest"
        port: 8984
      c:
        type: "Docker network"
        optional: true

services:
  veld:
    build: .
    ports:
      - 8984:8984
    healthcheck:
      test: curl -f admin:admin@localhost:8984/rest
      interval: 5s
      timeout: 5s
      retries: 1
      start_period: 5s
    command: basexhttp
